env:
  default:
    VERSION: "$(git describe --tags)"
    REGISTRY_ENDPOINT: "{{.registry.endpoint}}"
    REGISTRY_NAMESPACE: "{{.registry.namespace}}"
    REGISTRY_USERNAME: "{{.registry.username}}"
    REGISTRY_PASSWORD: "{{.registry.password}}"
    PULL_SECRET_NAME: "hatlonely-pull-secret"
    SECRET_NAME: "hatlonely-tls"
    HOST: "blog.hatlonely.com"

task:
  image:
    step:
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - docker build -t "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/blog:${VERSION}" -f Dockerfile .
      - docker push "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/blog:${VERSION}"
