env:
  default:
    HOST: blog.hatlonely.com

task:
  hexo:
    step:
      - |
        WORK_ROOT=$(pwd)
        hexo init $TMP/$HOST
        for path in $(find markdown -type f -name "*.md"); do
          cp $path $TMP/$HOST/source/_posts
        done
        cd $TMP/$HOST
        npm i hexo-theme-stellar
        cp ${WORK_ROOT}/hexo/* .
